=== uber/zanzibar/docs/client_config_schema.json
{
	"$id": "client config",
	"type": "object",
	"$schema": "http://json-schema.org/draft-06/schema#",
	"properties": {
		"name": {
			"type": "string",
			"description": "Client name",
			"examples": [
				"contacts"
			]
		},
		"type": {
			"type": "string",
			"description": "Client type, either http, tchannel or custom",
			"enum": [
				"http",
				"tchannel",
				"custom"
			],
			"examples": [
				"http"
			]
		},
		"config": {
			"type": "object",
			"properties": {
				"idlFile": {
					"type": "string",
					"description": "Path to client thrift file, relative to idl path",
					"examples": [
						"clients/contacts/contacts.thrift"
					]
				},
				"idlFileSha": {
					"type": "string",
					"description": "Sha of the thrift file, reserved but currently not used",
					"examples": [
						"{{placeholder}}"
					]
				},
				"exposedMethods": {
					"type": "object",
					"description": "The thrift methods exposed on the client in Go, key is method name in Go, value is thrift method in form of service::method",
					"examples": [
						"{\"SaveContacts\": \"Contacts::saveContacts\"}"
					]
				},
				"fixture": {
					"type": "object",
					"properties": {
						"importPath": {
							"type": "string",
							"description": "Package import path for concrete fixtures",
							"examples": [
								"github.com/uber/zanzibar/examples/example-gateway/clients/contacts/fixture"
							]
						},
						"scenarios": {
							"type": "object",
							"description": "Fixture scenarios, key is client method name, value is a list of string indicating different scenarios",
							"examples": [
								"{\"SaveContacts\": [\"success\"]}"
							]
						}
					}
				}
			}
		},
		"dependencies": {
			"type": "object",
			"properties": {
				"client": {
					"type": "array",
					"items": {
						"type": "string",
						"description": "Name of the client this client depends on",
						"examples": [
							"foo"
						]
					}
				}
			}
		}
	},
	"required": [
		"name",
		"type",
		"config",
		"dependencies"
	]
}

=== uber/zanzibar/examples/example-gateway/endpoints/baz/endpoint-config.json
{
	"name": "baz",
	"type": "http",
	"config": {
		"rateLimit": 100,
		"endpoints": [
			"call.json",
			"compare.json",
			"ping.json",
			"silly_noop.json",
			"trans.json",
			"trans-headers.json",
			"trans-headers-type.json",
			"trans-headers-no-req.json",
			"header-schema.json",
			"get-profile.json"
		]
	},
	"dependencies": {
		"client": [
			"baz"
		]
	}
}

=== uber/zanzibar/examples/example-gateway/endpoints/bar/endpoint-config.json
{
	"name": "bar",
	"type": "http",
	"config": {
		"rateLimit": 100,
		"endpoints": [
			"arg_not_struct.json",
			"arg_with_headers.json",
			"arg_with_query_params.json",
			"arg_with_nested_query_params.json",
			"arg_with_query_header.json",
			"arg_with_params.json",
			"arg_with_many_query_params.json",
			"missing_arg.json",
			"no_request.json",
			"normal.json",
			"too_many_args.json"
		]
	},
	"dependencies": {
		"client": [
			"bar"
		]
	}
}
